#!/bin/bash

# chkconfig: 3 99 05
# description: Newshound's fetch and stats daemon service
# processname: fetchd 

BIN_PATH=/opt/newshound/bin
SERVICE=$BIN_PATH/fetchd
PID_FILE=/var/run/fetchd.pid

function launchDaemon() {
    local id
    checkRunning
    id=$?
    if [ $id -eq 0 ]
    then
        touch $PID_FILE
        cd $BIN_PATH
        $SERVICE & echo $! > $PID_FILE
        echo "fetchd started"
    else
        echo "fetchd is running already"
    fi
}

function stopDaemon() {
    local is_running
    local id
    checkRunning
    is_running=$?
    if [ $is_running -eq 1 ]
    then
        id=`cat $PID_FILE`
        kill $id
        if [ $? -eq 0 ]
        then
            echo "fetchd stopped"
        else
            echo "Unable to stop fetchd"
        fi
    else
        echo "fetchd is stopped already"
    fi
}

function checkRunning() {   
    local id
    id=`cat $PID_FILE`
    if [ -z $id ]
    then
        return 0
    elif [ -d "/proc/$id" ]
    then
        return 1
    else
        return 0
    fi
}

function main {
    local is_running
    case "$1" in
    start)
        launchDaemon
    ;;
    stop)
        stopDaemon
    ;;
    status)
        checkRunning
        is_running=$?
        if [ $is_running -eq 1 ]
        then
            echo "fetchd is running..."
        else
            echo "fetchd is not running"
        fi
    ;;
    restart)
        stopDaemon
        sleep 1
        launchDaemon
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
    ;;
    esac
}

main $1
