runtime: go111
service: barkd

automatic_scaling:
  max_idle_instances: 1

env_variables:
  SLACK_KEYS: "{{ .SLACK_KEYS }}"
  TWITTER_TOKENS: "{{ .TWITTER_TOKENS }}"
  TWITTER_SECRETS: "{{ .TWITTER_SECRETS }}"
  TWITTER_CONSUMERS: "{{ .TWITTER_CONSUMERS }}"
  TWITTER_CONSUMER_SECRETS: "{{ .TWITTER_CONSUMER_SECRETS }}"
  AUTH_ID_AUDIENCE: "newshound.appspot.com"
