#!/bin/bash

# chkconfig: 3 99 05
# description: The the Noun Phrase extractor service
# processname: np_extractor 

BIN_PATH=/opt/newshound/bin
SERVICE=$BIN_PATH/np_extractor_run.py
PID_FILE=/var/run/np_extractor.pid
LOGDIR=/var/log/np_extractor
LOG=$LOGDIR/np_extractor.log

function launchDaemon() {
    local id
    checkRunning
    id=$?
    if [ $id -eq 0 ]
    then
        touch $PID_FILE
        mkdir -p $LOGDIR
        cd $BIN_PATH
        python $SERVICE >> $LOG 2>&1 & echo \$! > $PID_FILE
        echo "np_extractor started"
    else
        echo "np_extractor is running already"
    fi
}

function stopDaemon() {
    local is_running
    local id
    checkRunning
    is_running=$?
    if [ $is_running -eq 1 ]
    then
        id=`cat $PID_FILE`
        kill $id
        if [ $? -eq 0 ]
        then
            echo "np_extractor stopped"
        else
            echo "Unable to stop dashboard_service"
        fi
    else
        echo "np_extractor is stopped already"
    fi
}

function checkRunning() {   
    local id
    id=`cat $PID_FILE`
    if [ -z $id ]
    then
        return 0
    elif [ -d "/proc/$id" ]
    then
        return 1
    else
        return 0
    fi
}

function main {
    local is_running
    case "$1" in
    start)
        launchDaemon
    ;;
    stop)
        stopDaemon
    ;;
    status)
        checkRunning
        is_running=$?
        if [ $is_running -eq 1 ]
        then
            echo "np_extractor is running..."
        else
            echo "np_extractor is not running"
        fi
    ;;
    restart)
        stopDaemon
        sleep 1
        launchDaemon
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
    ;;
    esac
}

main $1
